### ISSUE TITLE
Can you add a shutdown section to the end? See comments pls.

### ISSUE THREAD

**Issue by ghost** [TIY-Austin-Front-End-Engineering/Curriculum#3]
Sorry for so many issues. Can you add a "what to do when you're shutting down section" to this. I know some of the instructions are nested in there but it would be nice to have them in one section. 

I see myself using Sails to build my own apps so I'm trying to make sure I have a decent cheat sheet to go back to.

**Comment by alarner** [comment]
I've moved the documentation into the sails-template repo and added a shutting down section. Thanks for the great suggestions!

https://github.com/TIY-Austin-Front-End-Engineering/sails-template
